### ISSUE TITLE
Enhance MongoDB Credential Security and AWS Access Management

### ISSUE THREAD

**Issue by rblessings** [rblessings/urlradar#42]
To ensure a robust security posture for MongoDB and AWS access, implement the following improvements:

1. **Secure MongoDB Credentials:**
   - Replace hardcoded credentials in the `application.yml` or `application.properties` file with Kubernetes Secrets.
   - Use a secret to store sensitive data like `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD`.
   - Update the Spring configuration to reference these secrets dynamically.

2. **Leverage AWS Secrets Manager:**
   - Implement AWS Secrets Manager to store and manage MongoDB credentials.
   - Enable dynamic rotation of secrets to minimize security risks.
   - Use the AWS SDK in the application to fetch credentials securely at runtime.

3. **Implement IRSA (IAM Roles for Service Accounts):**
   - Configure an IAM Role with fine-grained permissions for accessing AWS Secrets Manager.
   - Associate the IAM Role with the Kubernetes service account used by the application.
   - Ensure that only the necessary permissions are granted to follow the principle of least privilege.

4. **Ensure Encryption:**
   - Enable encryption at rest for MongoDB data using storage-class parameters.
   - Secure all communication between the application and MongoDB by enforcing TLS/SSL connections.
   - Configure AWS Secrets Manager to encrypt secrets using a Customer Managed Key (CMK) in AWS KMS.

**Tasks:**

1. **Store Credentials in Kubernetes Secrets:**
   - Create a Kubernetes Secret:
     ```yaml
     apiVersion: v1
     kind: Secret
     metadata:
       name: mongodb-credentials
     type: Opaque
     data:
       username: <base64-encoded-username>
       password: <base64-encoded-password>
     ```
   - Update Spring configuration to reference the secret:
     ```yaml
     spring:
       data:
         mongodb:
           uri: mongodb://${MONGO_INITDB_USERNAME}:${MONGO_INITDB_PASSWORD}@mongodb-svc:27017/urlradar?authSource=admin
     ```

2. **Integrate AWS Secrets Manager:**
   - Store MongoDB credentials in AWS Secrets Manager.
   - Fetch the credentials dynamically in the application:
     ```java
     @Bean
     public String mongoUri(AwsSecretsManagerClient secretsClient) {
         String secret = secretsClient.getSecretValue(GetSecretValueRequest.builder()
                 .secretId("mongodb/credentials")
                 .build()).secretString();
         JSONObject json = new JSONObject(secret);
         return "mongodb://" + json.getString("username") + ":" + json.getString("password") + "@mongodb-svc:27017/urlradar?authSource=admin";
     }
     ```

3. **Configure IRSA:**
   - Create an IAM Role with permissions for accessing the specific secret in AWS Secrets Manager.
   - Associate the IAM Role with the application's Kubernetes service account:
     ```yaml
     apiVersion: iam.amazonaws.com/v1
     kind: ServiceAccount
     metadata:
       name: app-service-account
       namespace: default
       annotations:
         eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/<role-name>
     ```

4. **Validate and Test:**
   - Verify that credentials are fetched correctly from Kubernetes Secrets and AWS Secrets Manager.
   - Ensure MongoDB connections are encrypted and functioning as expected.
   - Monitor for any access or permission issues.

**Acceptance Criteria:**
- MongoDB credentials are securely stored and managed.
- AWS Secrets Manager and IRSA are implemented for secure credential access.
- Encryption is enforced for both data at rest and in transit.
- Configuration changes are thoroughly tested and documented.
