### ISSUE TITLE
Refactor Spring Configuration into Environment-Specific Profiles

### ISSUE THREAD

**Issue by rblessings** [rblessings/urlradar#43]
To improve maintainability and facilitate environment-specific configurations, refactor the current `application.yml` into multiple `application-{profile}.yml` files. This approach will help streamline the configuration management process, reduce merge conflicts across teams, and ensure better separation of concerns between different environments (e.g., `dev`, `test`, `prod`).

---

### Tasks:

1. **Extract Configuration:**
   - Move shared configurations to `application.yml` (common base).
   - Create profile-specific files such as `application-dev.yml` and `application-prod.yml` for environment-specific overrides.

2. **Refactor `application.yml`:**
   - Retain shared settings:
     ```yaml
     spring:
       application:
         name: urlradar

     logging:
       level:
         org.springframework.web: INFO
         org.springframework.security: INFO
     ```

3. **Create `application-dev.yml`:**
   - Add `dev` environment-specific configurations:
     ```yaml
     spring:
       config:
         activate:
           on-profile: dev

       security:
         oauth2:
           resourceserver:
             jwt:
               issuer-uri: http://localhost:9000

       data:
         mongodb:
           uri: mongodb://root:root@localhost:27017/urlradar?authSource=admin

         redis:
           host: localhost
           port: 6379

       kafka:
         bootstrap-servers: http://localhost:9092

     logging:
       level:
         org.springframework.web: DEBUG
         org.springframework.security: TRACE
         org.springframework.data.mongodb: DEBUG
     ```

4. **Create `application-prod.yml`:**
   - Add `prod` environment-specific configurations:
     ```yaml
     spring:
       config:
         activate:
           on-profile: prod

       security:
         oauth2:
           resourceserver:
             jwt:
               issuer-uri: http://auth-server-svc.default.svc.cluster.local:8080

       data:
         mongodb:
           uri: mongodb://${MONGO_INITDB_USERNAME}:${MONGO_INITDB_PASSWORD}@mongodb-svc:27017/urlradar?authSource=admin

         redis:
           host: redis-svc
           port: 6379

       kafka:
         bootstrap-servers: kafka-svc:9092

     management:
       endpoints:
         web:
           exposure:
             include:
               - health
               - prometheus
               - info
       endpoint:
         health:
           show-details: always
         prometheus:
           enabled: true
     ```

5. **Activate Profiles Dynamically:**
   - Use the `SPRING_PROFILES_ACTIVE` environment variable to select the active profile during deployment.

6. **Test:**
   - Verify that configurations are loaded correctly for each profile (`dev`, `prod`).
   - Ensure no redundant or conflicting configurations exist.

---

**Acceptance Criteria:**
- All environment-specific configurations are extracted into separate profile files.
- Common configurations are retained in the base `application.yml`.
- Deployment environments can dynamically activate the appropriate profile using `SPRING_PROFILES_ACTIVE`.
- No merge conflicts arise from differing configurations between teams or environments.
